### ISSUE TITLE
Pursuit version does not have working pursuits/heat

### ISSUE THREAD

**Issue by ipkpjersi** [clya900/NFSMWFreeRunMod#1]
Hello,

I tested the pursuit version with a clean install of MW 2005 Redux. The Free Run map itself works fine, and works both with and without the extra options mod, but for some reason pursuits/heat does not work - the police never chase me, I never see them on the mini-map, etc. The police work in other modes just not in the Free Run map. 

Are there possibly any debug logs I could upload to help troubleshoot this issue?

Thanks.

**Comment by ipkpjersi** [comment]
Just tested with Vanilla Most Wanted v1.3, there are no police patrolling and there is no way to gain bounty, no pursuits/heat/etc: 

![](https://i.imgur.com/ADRptfK.png)

**Comment by cyo93** [comment]
Thanks for bringing up this issue.
Unfortunately, since this mod is an edit to the gameplay.bin file in Need For Speed Most Wanted, there are no debug logs that can be directly implemented to the new race. However, debug logs are planned for the script that edits the executable.
It seems like you don't have NFSMW Race Fixes by nglzrgn installed, you need to install the mod and set the Heat Level in the race settings to maximum in order for pursuit support to work. A permanent solution for users who don't want to install the RaceFixes mod is in the works and I hope to finish it as soon as possible (giving the proper credit to nglzrgn for implementing the quick race option in my code).

**Comment by ipkpjersi** [comment]
Hey,

Thanks for the response, I will give that a try tomorrow and report back with how that goes.

I observed similar behaviour in the NFS Carbon version of this mod - police never follow/chase me and never seem to spawn. Is there a similar workaround/fix for NFS Carbon police pursuits with this NFS Carbon mod?

Cheers.

**Comment by cyo93** [comment]
Unfortunately, I'm still working on this feature for Need for Speed Carbon Free Run and using NFSC Extra Options to test the pursuits in Need For Speed Carbon, and it's having some issues. Such issues include the pursuit information not showing up and the chase theme not playing properly, so in the meantime, pursuits are not supported in the Free Run Mod of Need For Speed Carbon.

**Comment by clya900** [comment]
Of course, I'm using Extra Options to test the pursuits in Need For Speed Carbon.

**Comment by ipkpjersi** [comment]
Yep can confirm with NFSMW Race Fixes by nglzrgn it works as expected with full pursuits, multiple heat levels, chase theme, pursuit breakers, etc so I'm closing this issue.

Hopefully one day you'll be able to get pursuits working in Need For Speed Carbon too, that would be amazing.
